## image with package numpy

In [3]:
import cv2
import numpy as np
import random

In [5]:
# [B G R]

rows = 300
cols = 300
img = np.zeros((rows, cols, 3), np.uint8)

for row in range(rows):
    for col in range(cols):
        img[row][col] = [random.randint(0,255), random.randint(0,255), random.randint(0,255)]

cv2.imwrite("image/mosaic.png", img)
cv2.imshow('test', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
img = np.zeros((500, 500, 3), dtype='uint8')
print(img)
img[150:350, 150:350] = [0,0,255]
print(img[150:170, 150:170])
# print(img.size)

cv2.imwrite("image/test1.jpg", img)
cv2.imshow("test1", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 ...

 [[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  ...
  [  0

In [9]:
# astronaut with mosaic
img = cv2.imread('image/astronaut_pixabay.png')
print(img.shape)
print(img.shape[1])

for row in range(img.shape[0]-300, img.shape[0]-265):
    for col in range(img.shape[1]):
        img[row][col] = [random.randint(0,255), random.randint(0,255), random.randint(0,255)]

cv2.imwrite("image/astronaut_pixabay_mosaic.png", img)
cv2.imshow('test', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

(640, 640, 3)
640


In [10]:
# plot simple synbols

img = np.zeros((600, 600), np.uint8)
cv2.rectangle(img, (0,0), (400, 200), (255,0,0), cv2.FILLED)
cv2.line(img, (0,0), (img.shape[1], img.shape[0]), (255,0,0), 5)
cv2.circle(img, (300, 400), 30, (255,0,0), cv2.FILLED)
cv2.putText(img, 'Hello', (100, 500), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2)
cv2.imwrite("image/hello.png", img)
cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()