In [1]:
import cv2
import numpy as np

In [ ]:
# import model
detector = cv2.CascadeClassifier('training_model/haarcascade_frontalface_default.xml')
# create the recognizer
recog = cv2.face.LBPHFaceRecognizer_create()
# for saving faces region
faces = []
# for saving faces iD
ids = []

# we can have as many faces as possible
# here, I only use 4 pictures to train the model
for i in range(1,5):
    img = cv2.imread("image/face01/face01_" + str(i) + ".png")
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    img_np = np.array(gray,'uint8')
    face = detector.detectMultiScale(gray)

    for(x,y,w,h) in face:
        faces.append(img_np[y:y+h,x:x+w])
        ids.append(1)

# model save
print('training...')
recog.train(faces,np.array(ids))
recog.save('face01.yml')
print('ok!')


training...
ok!


In [ ]:
# use the recognizer model we just construct
recognizer = cv2.face.LBPHFaceRecognizer_create()
recognizer.read('face01.yml')
cascade_path = "training_model/haarcascade_frontalface_default.xml"
face_cascade = cv2.CascadeClassifier(cascade_path)

# read a new face picture
img = cv2.imread('image/face01/face01_test1.png')
grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) 
img_np = np.array(gray,'uint8')

# start recognizing
img = cv2.resize(img,(540,300))
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY) 
faces = face_cascade.detectMultiScale(gray)
face = detector.detectMultiScale(gray)
print(face)

# construct face ID
name = {'1':'Tsai','2':'otherwise'}

for(x,y,w,h) in faces:
    cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),2)
    idnum,confidence = recognizer.predict(grey[y:y+h,x:x+w])# confidence interval
    if confidence < 60:
        text = name[str(idnum)]
    else:
        text = 'Unknown'
    # add text
    cv2.putText(img, text, (x,y-5),cv2.FONT_HERSHEY_SIMPLEX, 1, (0,255,0), 2, cv2.LINE_AA)


cv2.imshow('test', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[337  39  60  60]
 [290  67  62  62]
 [172  58  68  68]]
