# packages > module > function

   ```python
   import _package_or_module_or_function
   ```

   1. package
   ```python
   import numpy as np
   ```

   2. module
   ```python
   import matplotlib.pyplot as plt
   ```

   3. function
   ```python
   from numpy.random import random
   ```

In [5]:
import numpy as np
print(np.random.random())
print(np.random.random(size=3))
print(np.random.random(size=(3,4)))

0.5346087793325548
[0.02755566 0.46728511 0.3991756 ]
[[0.37051866 0.40773355 0.31430468 0.28698031]
 [0.62799666 0.3286379  0.42546859 0.98954672]
 [0.73258836 0.68462399 0.01550483 0.19858377]]


In [12]:
from numpy.random import normal

normal_dist = normal(loc=0, scale=1, size=(3,4))
print(type(normal_dist))
print(normal_dist.ndim)
print(normal_dist.size)
print(normal_dist.shape)
print(normal_dist.dtype)
print(normal_dist)
print('\n')
beta = 0.5
print(normal_dist * beta)
print('\n')
print(normal_dist.sum())
print(normal_dist.sum(axis=0)) # column
print(normal_dist.sum(axis=1)) # row



<class 'numpy.ndarray'>
2
12
(3, 4)
float64
[[-0.12449375 -0.50433758  0.5976375  -0.23326571]
 [-1.07767515  1.02512553  0.34346067 -2.60358852]
 [ 0.85881286  0.18038721 -1.00139788 -0.72813882]]


[[-0.06224687 -0.25216879  0.29881875 -0.11663286]
 [-0.53883758  0.51256276  0.17173034 -1.30179426]
 [ 0.42940643  0.0901936  -0.50069894 -0.36406941]]


-3.26747364944873
[-0.34335604  0.70117516 -0.06029971 -3.56499306]
[-0.26445954 -2.31267747 -0.69033664]


In [76]:
from numpy import random
import pandas as pd

random.seed(1234)
student_num = 50

scores = random.randint(50, 101, size=(student_num, 5))
df = pd.DataFrame(scores, columns=['MATH','ENG','BIO','PHY','GEO'], index=[f"PH{x}" for x in range(1, student_num + 1)])
print(df.tail(5))
print('======================================')

df.columns.name = 'SUBJECT'
df.index.name = 'ID'
print(df.tail(5))
print('======================================')

# calculate every subject's average
subject_mean = df.mean().to_frame('MEAN').T
print(subject_mean)
print('======================================')

# combine the data frame
combined_df = pd.concat([df, subject_mean])
print(combined_df.tail(6))
print('======================================')

# calculate every student's average scores
student_mean = df.mean(axis=1).to_frame()
print(student_mean.tail(5))
print('======================================')

combined_df = pd.concat([combined_df, student_mean],axis=1)
print(combined_df.tail(5))

# print((80+85+69+98+59)/5) # 78.2

      MATH  ENG  BIO  PHY  GEO
PH46    76   75   93   73   52
PH47    90   51   75   77   64
PH48    54   77   92   53   67
PH49    97   82   63   98   91
PH50    80   85   69   98   59
SUBJECT  MATH  ENG  BIO  PHY  GEO
ID                               
PH46       76   75   93   73   52
PH47       90   51   75   77   64
PH48       54   77   92   53   67
PH49       97   82   63   98   91
PH50       80   85   69   98   59
SUBJECT   MATH    ENG   BIO    PHY    GEO
MEAN     77.32  76.54  76.3  75.32  76.64
SUBJECT   MATH    ENG   BIO    PHY    GEO
PH46     76.00  75.00  93.0  73.00  52.00
PH47     90.00  51.00  75.0  77.00  64.00
PH48     54.00  77.00  92.0  53.00  67.00
PH49     97.00  82.00  63.0  98.00  91.00
PH50     80.00  85.00  69.0  98.00  59.00
MEAN     77.32  76.54  76.3  75.32  76.64
         0
ID        
PH46  73.8
PH47  71.4
PH48  68.6
PH49  86.2
PH50  78.2
       MATH    ENG   BIO    PHY    GEO     0
PH47  90.00  51.00  75.0  77.00  64.00  71.4
PH48  54.00  77.00  92.0  53.00